import { Product, StoreInfo } from '../types';

export const STORES_INFO: StoreInfo[] = [
  {
    id: 'lighthouse',
    name: 'Light House',
    tagline: 'Illuminating Spaces with Architectural & Decorative Lighting',
    address: 'Main Commercial Hub, Near City Center',
    city: 'Main Branch',
    mapsUrl: 'https://maps.app.goo.gl/oX5BepWoruLiGGxa6',
    phone: '+91 98765 43210',
    whatsapp: '919876543210',
    email: 'contact@lighthouse-electrical.com',
    operatingHours: 'Mon - Sat: 9:30 AM - 8:30 PM',
    specialties: ['Custom Chandeliers', 'Architectural LED Tracks', 'Outdoor & Facade Lights', 'Smart Home Lighting'],
    bannerImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'electrical_shop',
    name: 'Electrical Shop',
    tagline: 'Your Trusted Hub for Major Appliances, Wires & Smart Electronics',
    address: 'Station Road, Electronics Market',
    city: 'Appliance Hub',
    mapsUrl: 'https://maps.app.goo.gl/ie2eCof9c5GmTpdaA',
    phone: '+91 98765 43211',
    whatsapp: '919876543211',
    email: 'appliances@lighthouse-electrical.com',
    operatingHours: 'Mon - Sat: 9:30 AM - 9:00 PM',
    specialties: ['5-Star Energy Appliances', 'Industrial & Domestic Wiring', 'Heavy Inverters & Batteries', 'Modular Switches'],
    bannerImage: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
  }
];

export const LIGHT_CATEGORIES = [
  'All Lighting',
  'Chandeliers & Crystal',
  'Pendant & Hanging Lights',
  'LED Panels & Profile Lights',
  'Track & Spotlight Systems',
  'Outdoor & Landscape Lighting',
  'Decorative Wall Sconces',
  'Smart Ambient & RGB'
];

export const APPLIANCE_CATEGORIES = [
  'All Appliances',
  'Air Conditioners',
  'Refrigerators',
  'Washing Machines',
  'Ceiling & BLDC Fans',
  'Water Heaters & Geysers',
  'Kitchen & Induction'
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- LIGHT HOUSE PRODUCTS ---
  {
    id: 'lh-1',
    title: 'Nordic Minimalist Ring Pendant Light',
    brand: 'Lumina Lux',
    type: 'light',
    shopOrigin: 'lighthouse',
    category: 'Pendant & Hanging Lights',
    originalPrice: 14999,
    discountPrice: 10999,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 12,
    imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Ultra-thin brass finish LED ring pendant with tri-color dimmable light controls. Ideal for modern dining tables, living lounges, and office receptions.',
    specifications: [
      { label: 'Wattage', value: '45W Warm/Neutral/Cool' },
      { label: 'Material', value: 'Anodized Aluminum & Acrylic' },
      { label: 'Diameter', value: '80 cm' },
      { label: 'Warranty', value: '2 Years Manufacturer' }
    ],
    tags: ['Best Seller', 'Tri-Color', 'Dimmable'],
    rating: 4.9,
    reviewsCount: 28,
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-01-10T10:00:00.000Z'
  },
  {
    id: 'lh-2',
    title: 'Imperial Modern K9 Crystal Chandelier',
    brand: 'Royal Glow',
    type: 'light',
    shopOrigin: 'lighthouse',
    category: 'Chandeliers & Crystal',
    originalPrice: 42000,
    discountPrice: 32999,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 5,
    imageUrl: 'https://images.unsplash.com/photo-1543198181-e619b695113c?auto=format&fit=crop&w=800&q=80',
    description: 'Multi-tiered cascading K9 crystal chandelier with electroplated golden frame. Adds opulent splendor to foyer entrances, high-ceiling hallways, and grand living halls.',
    specifications: [
      { label: 'Bulb Type', value: '18 x E14 LED Bulbs Included' },
      { label: 'Finish', value: '24K Electroplated Gold' },
      { label: 'Dimensions', value: '110cm Height x 75cm Width' },
      { label: 'Warranty', value: '3 Years Warranty' }
    ],
    tags: ['Luxury', 'Crystal', 'Festive Offer'],
    rating: 5.0,
    reviewsCount: 14,
    createdAt: '2026-01-12T10:00:00.000Z',
    updatedAt: '2026-01-12T10:00:00.000Z'
  },
  {
    id: 'lh-3',
    title: 'Magnetic Architectural Track Light System (2m Rail)',
    brand: 'RayPro',
    type: 'light',
    shopOrigin: 'lighthouse',
    category: 'Track & Spotlight Systems',
    originalPrice: 11500,
    discountPrice: 8999,
    isFeatured: false,
    stockStatus: 'in_stock',
    stockQuantity: 20,
    imageUrl: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=800&q=80',
    description: 'Sleek surface/recessed 48V magnetic track system with 3 interchangeable module heads (Foldable floodlight, Spot beam, and Linear diffuser).',
    specifications: [
      { label: 'System Voltage', value: '48V Low Voltage Safety' },
      { label: 'Length', value: '2 Meters Aluminium Track' },
      { label: 'Modules Included', value: '1x Linear (12W), 2x Spot (10W)' },
      { label: 'CRI', value: '>90 High Color Accuracy' }
    ],
    tags: ['Architectural', 'Modular', '48V Safe'],
    rating: 4.8,
    reviewsCount: 19,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z'
  },
  {
    id: 'lh-4',
    title: 'COB Aluminum Slim Profile Light with Silicon Diffuser',
    brand: 'NeoLine',
    type: 'light',
    shopOrigin: 'lighthouse',
    category: 'LED Panels & Profile Lights',
    originalPrice: 2800,
    discountPrice: 1999,
    isFeatured: false,
    stockStatus: 'in_stock',
    stockQuantity: 50,
    imageUrl: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&w=800&q=80',
    description: 'Seamless continuous cove and ceiling illumination profile light strip with dot-free high-density COB LEDs.',
    specifications: [
      { label: 'Power Density', value: '15W per meter' },
      { label: 'Color Temp', value: '3000K Warm White / 4000K Natural' },
      { label: 'IP Rating', value: 'IP20 Indoor / IP65 Kitchen ready' },
      { label: 'Length', value: '5 Meters Roll + Profile' }
    ],
    tags: ['Dotless COB', 'Custom Cut'],
    rating: 4.7,
    reviewsCount: 32,
    createdAt: '2026-01-18T10:00:00.000Z',
    updatedAt: '2026-01-18T10:00:00.000Z'
  },
  {
    id: 'lh-5',
    title: 'Waterproof Dual-Way LED Facade Wall Sconce',
    brand: 'Lighthouse Exterior',
    type: 'light',
    shopOrigin: 'lighthouse',
    category: 'Outdoor & Landscape Lighting',
    originalPrice: 3800,
    discountPrice: 2699,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 15,
    imageUrl: 'https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?auto=format&fit=crop&w=800&q=80',
    description: 'Heavy duty die-cast aluminum up-and-down outdoor architectural wall sconce. Weatherproof IP67 rating built to withstand heavy rain and harsh direct sunlight.',
    specifications: [
      { label: 'Wattage', value: '12W Bridgelux LED' },
      { label: 'Waterproof', value: 'IP67 Rated' },
      { label: 'Body Finish', value: 'Matt Black Anti-rust Coating' },
      { label: 'Beam Angle', value: 'Adjustable Shutters 0-100°' }
    ],
    tags: ['IP67 Waterproof', 'Adjustable Beam'],
    rating: 4.9,
    reviewsCount: 22,
    createdAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-01-20T10:00:00.000Z'
  },
  {
    id: 'lh-6',
    title: 'Smart RGBWW Wi-Fi Ambient Corner Floor Lamp',
    brand: 'AuraSmart',
    type: 'light',
    shopOrigin: 'lighthouse',
    category: 'Smart Ambient & RGB',
    originalPrice: 7999,
    discountPrice: 5499,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 8,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    description: '16 Million colors + Dynamic music sync corner ambient light bar controlled via Alexa, Google Home, and Smartphone app.',
    specifications: [
      { label: 'Connectivity', value: '2.4GHz Wi-Fi + Bluetooth' },
      { label: 'Height', value: '142 cm' },
      { label: 'Modes', value: '300+ Dynamic Lighting Effects' },
      { label: 'App', value: 'Tuya / Smart Life Compatible' }
    ],
    tags: ['Smart Control', 'Alexa & Google', 'Music Sync'],
    rating: 4.8,
    reviewsCount: 41,
    createdAt: '2026-01-22T10:00:00.000Z',
    updatedAt: '2026-01-22T10:00:00.000Z'
  },

  // --- ELECTRICAL SHOP PRODUCTS ---
  {
    id: 'es-1',
    title: '1.5 Ton 5-Star AI Inverter Split AC',
    brand: 'Voltas / Carrier Tech',
    type: 'appliance',
    shopOrigin: 'electrical_shop',
    category: 'Air Conditioners',
    originalPrice: 52990,
    discountPrice: 38990,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 10,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    description: 'Heavy cooling inverter AC with 100% copper condenser, PM 2.5 filter, anti-bacterial coating, and fast cooling mode for hot summers.',
    specifications: [
      { label: 'Capacity', value: '1.5 Ton (Ideal for 150 sq ft)' },
      { label: 'Energy Rating', value: '5 Star ISEER 5.2' },
      { label: 'Coil Material', value: '100% Copper with Blue Fin Protection' },
      { label: 'Warranty', value: '10 Years Compressor Warranty' }
    ],
    tags: ['5 Star Energy', '10 Year Compressor Warranty', 'Hot Pick'],
    rating: 4.9,
    reviewsCount: 56,
    createdAt: '2026-01-11T10:00:00.000Z',
    updatedAt: '2026-01-11T10:00:00.000Z'
  },
  {
    id: 'es-2',
    title: '420L Convertible Double Door Frost Free Refrigerator',
    brand: 'LG Electronics',
    type: 'appliance',
    shopOrigin: 'electrical_shop',
    category: 'Refrigerators',
    originalPrice: 58900,
    discountPrice: 44990,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 6,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    description: '5-in-1 convertible smart inverter compressor refrigerator with express freezing, humidity controller, and toughened glass shelves.',
    specifications: [
      { label: 'Capacity', value: '420 Liters' },
      { label: 'Compressor', value: 'Smart Inverter (Super Silent)' },
      { label: 'Door Cooling+', value: 'Multi Air Flow Technology' },
      { label: 'Warranty', value: '1 Year Product + 10 Year Compressor' }
    ],
    tags: ['Convertible 5-in-1', 'Low Power Consumption'],
    rating: 4.8,
    reviewsCount: 37,
    createdAt: '2026-01-14T10:00:00.000Z',
    updatedAt: '2026-01-14T10:00:00.000Z'
  },
  {
    id: 'es-3',
    title: 'BLDC Ultra Energy-Saving Smart Ceiling Fan with Remote',
    brand: 'Atomberg / Havells',
    type: 'appliance',
    shopOrigin: 'electrical_shop',
    category: 'Ceiling & BLDC Fans',
    originalPrice: 4800,
    discountPrice: 3290,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 35,
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    description: 'Consumes only 28W at top speed, saving up to 65% electricity annually. Comes with smart remote controller, timer, and boost mode.',
    specifications: [
      { label: 'Motor Type', value: 'BLDC (Brushless DC Motor)' },
      { label: 'Power Consumption', value: '28W at Speed 5' },
      { label: 'Sweep Size', value: '1200 mm (48 inches)' },
      { label: 'Warranty', value: '3 Years On-Site Warranty' }
    ],
    tags: ['65% Power Saver', 'Remote Included', 'Top Rated'],
    rating: 4.9,
    reviewsCount: 89,
    createdAt: '2026-01-16T10:00:00.000Z',
    updatedAt: '2026-01-16T10:00:00.000Z'
  },
  {
    id: 'es-4',
    title: '25 Liter Digital Temperature Display Geyser / Water Heater',
    brand: 'Crompton / Bajaj',
    type: 'appliance',
    shopOrigin: 'electrical_shop',
    category: 'Water Heaters & Geysers',
    originalPrice: 12500,
    discountPrice: 8490,
    isFeatured: false,
    stockStatus: 'in_stock',
    stockQuantity: 14,
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80',
    description: 'Glass-lined titanium armor tank with digital temperature readout, eco mode, and 8-bar pressure capability suitable for high-rise buildings.',
    specifications: [
      { label: 'Capacity', value: '25 Liters' },
      { label: 'Pressure Rating', value: '8 Bar (High Rise Suitable)' },
      { label: 'Heating Element', value: 'Incoloy 800 Element' },
      { label: 'Warranty', value: '7 Years Tank Warranty' }
    ],
    tags: ['High-Rise Suitable', 'Digital LED Display'],
    rating: 4.7,
    reviewsCount: 26,
    createdAt: '2026-01-19T10:00:00.000Z',
    updatedAt: '2026-01-19T10:00:00.000Z'
  },
  {
    id: 'es-5',
    title: '8.0 Kg Fully Automatic Front Load Washing Machine',
    brand: 'Bosch / IFB',
    type: 'appliance',
    shopOrigin: 'electrical_shop',
    category: 'Washing Machines',
    originalPrice: 39900,
    discountPrice: 29990,
    isFeatured: true,
    stockStatus: 'in_stock',
    stockQuantity: 8,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80',
    description: 'Steam wash technology removing 99.9% germs, anti-tangle drum design, 1400 RPM spin speed for fast drying.',
    specifications: [
      { label: 'Capacity', value: '8.0 Kg' },
      { label: 'RPM', value: '1400 RPM High Spin' },
      { label: 'Wash Programs', value: '15 Customized Wash Modes' },
      { label: 'Inverter Motor', value: 'Direct Drive EcoSilence' }
    ],
    tags: ['Steam Wash', 'Inverter Motor'],
    rating: 4.8,
    reviewsCount: 31,
    createdAt: '2026-01-21T10:00:00.000Z',
    updatedAt: '2026-01-21T10:00:00.000Z'
  },
  {
    id: 'es-6',
    title: '2100W Smart Touch Feather Induction Cooktop',
    brand: 'Philips Tech',
    type: 'appliance',
    shopOrigin: 'electrical_shop',
    category: 'Kitchen & Induction',
    originalPrice: 4299,
    discountPrice: 2899,
    isFeatured: false,
    stockStatus: 'in_stock',
    stockQuantity: 25,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    description: 'Full glass crystal panel with micro-crystal plate, preset Indian cooking menus, auto shut-off safety sensor, and child lock.',
    specifications: [
      { label: 'Power', value: '2100 Watts Fast Heating' },
      { label: 'Panel', value: 'Full Glass Touch Control' },
      { label: 'Safety', value: 'Voltage Surge Protection' },
      { label: 'Warranty', value: '2 Years Replacement Warranty' }
    ],
    tags: ['Energy Efficient', 'Preset Cooking Menus'],
    rating: 4.6,
    reviewsCount: 48,
    createdAt: '2026-01-23T10:00:00.000Z',
    updatedAt: '2026-01-23T10:00:00.000Z'
  }
];
